sourcedir				:= src
output					:= debug
compileroptions			:= -g -Wall
includes				:= -I ./$(sourcedir)
outputfile				:= p2_vebt

objectfiles				:= BinaryHeap.o FibonacciHeap.o vebtrees.o RBTrees.o

prebuild:
	mkdir -p $(output)

build: BinaryHeap.o FibonacciHeap.o RBTrees.o vebtrees.o
	gcc $^ -o ./$(output)/$(outputfile)

all: prebuild build

clean:
	rm -f ./$(output)/BinaryHeap.o
	rm -f ./$(output)/FibonacciHeap.o
	rm -f ./$(output)/RBTrees.o
	rm -f ./$(output)/vebtrees.o
	rm -f ./$(output)/$(outputfile)

BinaryHeap.o: ./$(sourcedir)/BinaryHeap.c
	gcc $(compileroptions) $(includes) -c $< -o ./$(output)/$@

FibonacciHeap.o: ./$(sourcedir)/FibonacciHeap.c
	gcc $(compileroptions) $(includes) -c $< -o ./$(output)/$@

RBTrees.o: ./$(sourcedir)/RBTrees.cpp
	gcc $(compileroptions) $(includes) -c $< -o .	/$(output)/$@

vebtrees.o: ./$(sourcedir)/vebtrees.c
	gcc $(compileroptions) $(includes) -c $< -o .	/$(output)/$@